import Head from 'next/head';
import Navbar from '../../components/Navbar.js';

import styles from '../../styles/contact/Contact.module.css';
import { AiFillPhone } from 'react-icons/ai';
import { ImLocation } from 'react-icons/im';

import Footer from '../../components/footer/Footer.js';
import PrimaryButton from '../../components/buttons/PrimaryButton.js';

import { useCallback } from 'react';
import { loadFull } from 'tsparticles';
import Particles from 'react-particles';
import { particleConfig } from '../../lib/particle_config';

export default function Contact(){
  const particlesInit = useCallback(async engine => {
    await loadFull(engine);
  }, []);

  const particlesLoaded = useCallback(async container => {
    console.log(container);
  }, []);  

  return (
    <div className={styles.container}>
      <Head>
        <title> Charicha Insitute </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={'bg-gradient-[-45deg] from-eggblue to-slategray pb-10'}>
        <Navbar path='/contact'/>
        <Particles init={particlesInit} loaded={particlesLoaded} options={particleConfig}/>        
	<div className='px-8 md:px-10 xl:px-20 2xl:px-48 mt-10'>
          <div className='px-8'>
            <h2 className='text-2xl text-white'> Contact Us </h2>
            <p className='text-base text-white font-light'> Thank you for visiting our website. If you have any questions or would like to schedule a tour of our facilities, please don&apos;t hesitate to reach out to us. </p>
          </div>


          <div className={'flex flex-wrap gap-10 mt-10 justify-center'}>
          <form className={'w-full flex-1 flex flex-col gap-8 p-4 xl:p-12 bg-slategray rounded-2xl shadow-lg'}>
	    <p className='text-2xl text-white font-light border-b-2 border-b-cheeseyellow'> Contact Details </p>
            <input name="" type="text" className={styles["form-input"]} placeholder="First Name"/>
            <input name="" type="text"  className={styles["form-input"]} placeholder="Last Name"/>
            <input name="" type="email" className={styles["form-input"]} placeholder="Email"/>
            <input name="" type="number"  className={styles["form-input"]} placeholder="Phone Number"/>

            <textarea cols="30" id="" name="" rows="10" className={styles["text-area"]} placeholder="Your message here..."></textarea>
            <PrimaryButton text="Submit" onClick={()=> {
              console.log("something");
            }}/>
          </form>
          <div className={'flex-1 flex flex-col gap-4'}>
            <h2 className='text-2xl text-white'> Charicha Institute </h2>
            <p className={'text-white text-sm font-light'}> We look forward to hearing from you and helping you learn more about the exciting opportunities available at our computer institute. </p>

	    <div className='flex flex-col gap-2'>
              <p className={'flex text-white text-sm font-light items-center gap-2'}> <AiFillPhone color="blue"/>  +977 9817-388966 </p>
              <p className={'flex text-white text-sm font-light items-center gap-2'}> <ImLocation color="red"/> Belbari - 11, Laxmimarga </p>            
            </div>

	    <div className='w-full h-full rounded-2xl overflow-clip shadow-md'>
              <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14263.539457521121!2d87.4492403!3d26.6521686!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xec11a5cb93e0fac1!2sCharicha%20Institute!5e0!3m2!1sen!2suk!4v1672662347634!5m2!1sen!2suk" width="100%" height="100%" style={{'border': 0}} allowFullScreen="" loading="lazy" referrerPolicy="no-referrer-when-downgrade"></iframe>
            </div>

          </div>
        </div>
        </div>

      </main>

      <Footer/>

    </div>

  );

}
